#!/bin/sh
dbrootpwd=123456
/usr/local/mysql/bin/mysql -e "grant all privileges on *.* to root@'127.0.0.1' identified by \"${dbrootpwd}\" with grant option;"
 /usr/local/mysql/bin/mysql -e "grant all privileges on *.* to root@'localhost' identified by \"${dbrootpwd}\" with grant option;"
 /usr/local/mysql/bin/mysql -uroot -p${dbrootpwd} -e "delete from mysql.user where Password='';"
 /usr/local/mysql/bin/mysql -uroot -p${dbrootpwd} -e "delete from mysql.db where User='';"
 /usr/local/mysql/bin/mysql -uroot -p${dbrootpwd} -e "delete from mysql.proxies_priv where Host!='localhost';"
 /usr/local/mysql/bin/mysql -uroot -p${dbrootpwd} -e "drop database test;"
#/usr/local/mysql/bin/mysql -uroot -p${dbrootpwd} -e "reset master;"主从
  /usr/local/mysql/bin/mysql -uroot -p${dbrootpwd} -e  "flush privileges;"
